  
authors = ["William Herrera <wherrera@alahonua.com>"]
name = "SuffixTrees"
uuid = "430257b6-7d61-4797-9a77-8ecd01b73801"
version = "0.0.2"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
